### ISSUE TITLE
Interlinking Github and Cologne

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/csl-santam#1]
@funderburkjim well done. A link from http://www.sanskrit-lexicon.uni-koeln.de/scans/MWScan/tamil/index.html to https://github.com/sanskrit-lexicon/Cologne-Sanskrit-Tamil would make sense. Like "Download the source files".

**Comment by funderburkjim** [comment]
@gasyoun  Good idea!  

Done.
